version: 0.0
os: linux


files:
  - source: /
    destination: /root/instagram-server


permissions:
  - object: /
    owner: root
    group: root

hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: root