spring:
  application:
    name: dividend-financial

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/actualdividend?serverTimezone=Asia/Seoul
    username: root
    password: admin007!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    defer-datasource-initialization: true


  redis:
    host: localhost
    port: 6379

  jwt:
    secret: am9uZ3dvb2stZGl2aWRlbmQtcHJvamVjdAo=



scheduler:
  scrap:
    yahoo: "0 0 0 * * *"
